### PR TITLE
fix: disable sidebar option when no wallet is created

### PR DESCRIPTION
**Pull request by jhasuraj01**
image

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6311 On cysync If the wallets are missing, most of the things on the side bar like send crypto should be disabled](https://app.clickup.com/t/9002019994/PRF-6311)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6311 On cysync If the wallets are missing, most of the things on the side bar like send crypto should be disabled](https://app.clickup.com/t/9002019994/PRF-6311)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6311 On cysync If the wallets are missing, most of the things on the side bar like send crypto should be disabled](https://app.clickup.com/t/9002019994/PRF-6311)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6311 On cysync If the wallets are missing, most of the things on the side bar like send crypto should be disabled](https://app.clickup.com/t/9002019994/PRF-6311)

**Review by irshadCypherock — APPROVED** [review]

**Pull request merged**
