### PR TITLE
feat: open `walletActionsDialog` after onboarding

### PR DESCRIPTION
**Pull request by jhasuraj01**

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6385 On cysync after initial onboarding the Add wallet screen isn't coming automatically](https://app.clickup.com/t/9002019994/PRF-6385)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6385 On cysync after initial onboarding the Add wallet screen isn't coming automatically](https://app.clickup.com/t/9002019994/PRF-6385)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6385 On cysync after initial onboarding the Add wallet screen isn't coming automatically](https://app.clickup.com/t/9002019994/PRF-6385)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6385 On cysync after initial onboarding the Add wallet screen isn't coming automatically](https://app.clickup.com/t/9002019994/PRF-6385)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6385 On cysync after initial onboarding the Add wallet screen isn't coming automatically](https://app.clickup.com/t/9002019994/PRF-6385)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6385 On cysync after initial onboarding the Add wallet screen isn't coming automatically](https://app.clickup.com/t/9002019994/PRF-6385)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6385 On cysync after initial onboarding the Add wallet screen isn't coming automatically](https://app.clickup.com/t/9002019994/PRF-6385)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6385 On cysync after initial onboarding the Add wallet screen isn't coming automatically](https://app.clickup.com/t/9002019994/PRF-6385)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6385 On cysync after initial onboarding the Add wallet screen isn't coming automatically](https://app.clickup.com/t/9002019994/PRF-6385)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6385 On cysync after initial onboarding the Add wallet screen isn't coming automatically](https://app.clickup.com/t/9002019994/PRF-6385)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6385 On cysync after initial onboarding the Add wallet screen isn't coming automatically](https://app.clickup.com/t/9002019994/PRF-6385)

**Review by irshadCypherock — APPROVED** [review]

**Pull request merged**
