### PR TITLE
feat: prevent mini screen ui to show up

### PR DESCRIPTION
**Pull request by jhasuraj01**
Set `minWidth` and `minHeight` to device primary screen `width` and `height`

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6445 Increase cysync min resolution such that production mini design isn't visible to user](https://app.clickup.com/t/9002019994/PRF-6445)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6445 Increase cysync min resolution such that production mini design isn't visible to user](https://app.clickup.com/t/9002019994/PRF-6445)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6445 Increase cysync min resolution such that production mini design isn't visible to user](https://app.clickup.com/t/9002019994/PRF-6445)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6445 Increase cysync min resolution such that production mini design isn't visible to user](https://app.clickup.com/t/9002019994/PRF-6445)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6445 Increase cysync min resolution such that production mini design isn't visible to user](https://app.clickup.com/t/9002019994/PRF-6445)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6445 Increase cysync min resolution such that production mini design isn't visible to user](https://app.clickup.com/t/9002019994/PRF-6445)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6445 Increase cysync min resolution such that production mini design isn't visible to user](https://app.clickup.com/t/9002019994/PRF-6445)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6445 Increase cysync min resolution such that production mini design isn't visible to user](https://app.clickup.com/t/9002019994/PRF-6445)

**Review by ghost — APPROVED** [review]

**Pull request merged**
