### PR TITLE
fix: correct typos

### PR DESCRIPTION
**Pull request by ujjwal-cyph**
Fixes https://app.clickup.com/t/9002019994/PRF-6287
Fixes https://app.clickup.com/t/9002019994/PRF-6368

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6368 On cysync in top bar syncronized spelling is incorrect](https://app.clickup.com/t/9002019994/PRF-6368)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6287 On cysync in the dialogue box remove "our" from the message](https://app.clickup.com/t/9002019994/PRF-6287)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6368 On cysync in top bar syncronized spelling is incorrect](https://app.clickup.com/t/9002019994/PRF-6368)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6368 On cysync in top bar syncronized spelling is incorrect](https://app.clickup.com/t/9002019994/PRF-6368)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6287 On cysync in the dialogue box remove "our" from the message](https://app.clickup.com/t/9002019994/PRF-6287)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6287 On cysync in the dialogue box remove "our" from the message](https://app.clickup.com/t/9002019994/PRF-6287)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6287 On cysync in the dialogue box remove "our" from the message](https://app.clickup.com/t/9002019994/PRF-6287)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6287 On cysync in the dialogue box remove "our" from the message](https://app.clickup.com/t/9002019994/PRF-6287)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6368 On cysync in top bar syncronized spelling is incorrect](https://app.clickup.com/t/9002019994/PRF-6368)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6287 On cysync in the dialogue box remove "our" from the message](https://app.clickup.com/t/9002019994/PRF-6287)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6368 On cysync in top bar syncronized spelling is incorrect](https://app.clickup.com/t/9002019994/PRF-6368)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6368 On cysync in top bar syncronized spelling is incorrect](https://app.clickup.com/t/9002019994/PRF-6368)

**Review by irshadCypherock — APPROVED** [review]

**Pull request merged**
