### PR TITLE
fix: clear device logs when unchecked

### PR DESCRIPTION
**Pull request by ujjwal-cyph**
Fixes https://app.clickup.com/t/9002019994/PRF-6414

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6414 On cysync device logs are still getting attached and sent even after unchecking device logs](https://app.clickup.com/t/9002019994/PRF-6414)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6414 On cysync device logs are still getting attached and sent even after unchecking device logs](https://app.clickup.com/t/9002019994/PRF-6414)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6414 On cysync device logs are still getting attached and sent even after unchecking device logs](https://app.clickup.com/t/9002019994/PRF-6414)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6414 On cysync device logs are still getting attached and sent even after unchecking device logs](https://app.clickup.com/t/9002019994/PRF-6414)

**Review by irshadCypherock — APPROVED** [review]

**Pull request merged**
