### PR TITLE
fix: float icon within notification description

### PR DESCRIPTION
**Pull request by jhasuraj01**
image

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6447 On cysync in notifications the text alignment is not correct](https://app.clickup.com/t/9002019994/PRF-6447)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6447 On cysync in notifications the text alignment is not correct](https://app.clickup.com/t/9002019994/PRF-6447)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6447 On cysync in notifications the text alignment is not correct](https://app.clickup.com/t/9002019994/PRF-6447)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6447 On cysync in notifications the text alignment is not correct](https://app.clickup.com/t/9002019994/PRF-6447)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6447 On cysync in notifications the text alignment is not correct](https://app.clickup.com/t/9002019994/PRF-6447)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6447 On cysync in notifications the text alignment is not correct](https://app.clickup.com/t/9002019994/PRF-6447)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6447 On cysync in notifications the text alignment is not correct](https://app.clickup.com/t/9002019994/PRF-6447)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6447 On cysync in notifications the text alignment is not correct](https://app.clickup.com/t/9002019994/PRF-6447)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6447 On cysync in notifications the text alignment is not correct](https://app.clickup.com/t/9002019994/PRF-6447)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6447 On cysync in notifications the text alignment is not correct](https://app.clickup.com/t/9002019994/PRF-6447)

**Review by irshadCypherock — APPROVED** [review]

**Pull request merged**
