### PR TITLE
fix: show parent icon as sub-icon for clarity

### PR DESCRIPTION
**Pull request by ujjwal-cyph**
Fixes https://app.clickup.com/t/9002019994/PRF-6398
Fixes https://app.clickup.com/t/9002019994/PRF-6376

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6376 On cysync in receive flow in case of tokens the chain icon needs to be added in token icon ( Chain + token icon )](https://app.clickup.com/t/9002019994/PRF-6376)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6398 On cysync in portfolio screen there is not any difference between tokens for different chains](https://app.clickup.com/t/9002019994/PRF-6398)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6376 On cysync in receive flow in case of tokens the chain icon needs to be added in token icon ( Chain + token icon )](https://app.clickup.com/t/9002019994/PRF-6376)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6398 On cysync in portfolio screen there is not any difference between tokens for different chains](https://app.clickup.com/t/9002019994/PRF-6398)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6376 On cysync in receive flow in case of tokens the chain icon needs to be added in token icon ( Chain + token icon )](https://app.clickup.com/t/9002019994/PRF-6376)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6398 On cysync in portfolio screen there is not any difference between tokens for different chains](https://app.clickup.com/t/9002019994/PRF-6398)

**Review by irshadCypherock — DISMISSED** [review]

**Review by irshadCypherock — APPROVED** [review]

**Pull request merged**
