### PR TITLE
fix: transaction notifications

### PR DESCRIPTION
**Pull request by irshadCypherock**

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6446 On cysync the notification order(date) is wrong](https://app.clickup.com/t/9002019994/PRF-6446)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6464 On cysync in notifications the pending status icon needs to be replaced from green to yellow color](https://app.clickup.com/t/9002019994/PRF-6464)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6446 On cysync the notification order(date) is wrong](https://app.clickup.com/t/9002019994/PRF-6446)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6464 On cysync in notifications the pending status icon needs to be replaced from green to yellow color](https://app.clickup.com/t/9002019994/PRF-6464)

**Review by ghost — APPROVED** [review]

**Pull request merged**
