### PR TITLE
fix: prevent crash due to index out of bound error in line graph

### PR DESCRIPTION
**Pull request by jhasuraj01**

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6400 On cysync in Portfolio, in case of wallets having no accounts and when cursor is on graph then blank screen is coming](https://app.clickup.com/t/9002019994/PRF-6400)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6400 On cysync in Portfolio, in case of wallets having no accounts and when cursor is on graph then blank screen is coming](https://app.clickup.com/t/9002019994/PRF-6400)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6400 On cysync in Portfolio, in case of wallets having no accounts and when cursor is on graph then blank screen is coming](https://app.clickup.com/t/9002019994/PRF-6400)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6400 On cysync in Portfolio, in case of wallets having no accounts and when cursor is on graph then blank screen is coming](https://app.clickup.com/t/9002019994/PRF-6400)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6400 On cysync in Portfolio, in case of wallets having no accounts and when cursor is on graph then blank screen is coming](https://app.clickup.com/t/9002019994/PRF-6400)

**Review by irshadCypherock — APPROVED** [review]

**Pull request merged**
