### PR TITLE
fix: wallet connect bugs

### PR DESCRIPTION
**Pull request by ghost**
fixes:
https://app.clickup.com/t/9002019994/PRF-6492
https://app.clickup.com/t/9002019994/PRF-6487
https://app.clickup.com/t/9002019994/PRF-6474
https://app.clickup.com/t/9002019994/PRF-6452

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6487 On cysync in wallet connect flow the gnosis safe logo is not coming](https://app.clickup.com/t/9002019994/PRF-6487)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6492 On cysync in wallet connect flow if balances are low then it shows low balances below the amount which is "0"](https://app.clickup.com/t/9002019994/PRF-6492)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6474 On cysync in wallet connect flow the send max is enabled when communicating with dapp](https://app.clickup.com/t/9002019994/PRF-6474)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6452 On cysync in wallet connect the abort signal is not being to sent to device](https://app.clickup.com/t/9002019994/PRF-6452)

**Review by irshadCypherock — APPROVED** [review]

**Pull request merged**
