### PR TITLE
fix: remove question mark icon from text

### PR DESCRIPTION
**Pull request by ujjwal-cyph**
Fixes https://app.clickup.com/t/9002019994/PRF-6310

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6310 On cysync hide question marks and add support page in "Help ?" button](https://app.clickup.com/t/9002019994/PRF-6310)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6310 On cysync hide question marks and add support page in "Help ?" button](https://app.clickup.com/t/9002019994/PRF-6310)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6310 On cysync hide question marks and add support page in "Help ?" button](https://app.clickup.com/t/9002019994/PRF-6310)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6310 On cysync hide question marks and add support page in "Help ?" button](https://app.clickup.com/t/9002019994/PRF-6310)

**Review by irshadCypherock — APPROVED** [review]

**Pull request merged**
