### PR TITLE
fix: enable click navigation on token rows in wallet

### PR DESCRIPTION
**Pull request by ujjwal-cyph**
Fixes https://app.clickup.com/t/9002019994/PRF-6397

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6397 On cysync on clicking eth tokens it's not redirecting to respective token page](https://app.clickup.com/t/9002019994/PRF-6397)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6397 On cysync on clicking eth tokens it's not redirecting to respective token page](https://app.clickup.com/t/9002019994/PRF-6397)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6397 On cysync on clicking eth tokens it's not redirecting to respective token page](https://app.clickup.com/t/9002019994/PRF-6397)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6397 On cysync on clicking eth tokens it's not redirecting to respective token page](https://app.clickup.com/t/9002019994/PRF-6397)

**Review by irshadCypherock — APPROVED** [review]

**Pull request merged**
