### PR TITLE
fix: remove non-functional toggles and align table header

### PR DESCRIPTION
**Pull request by ujjwal-cyph**
Fixes https://app.clickup.com/t/9002019994/PRF-6420

Fixes https://app.clickup.com/t/9002019994/PRF-6416

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6420 On cysync in settings menu "Analytics and cysync update" section needs to be hidden](https://app.clickup.com/t/9002019994/PRF-6420)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6420 On cysync in settings menu "Analytics and cysync update" section needs to be hidden](https://app.clickup.com/t/9002019994/PRF-6420)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6416 On cysync in history section the "Time" text in header is not left aligned](https://app.clickup.com/t/9002019994/PRF-6416)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6416 On cysync in history section the "Time" text in header is not left aligned](https://app.clickup.com/t/9002019994/PRF-6416)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6420 On cysync in settings menu "Analytics and cysync update" section needs to be hidden](https://app.clickup.com/t/9002019994/PRF-6420)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6420 On cysync in settings menu "Analytics and cysync update" section needs to be hidden](https://app.clickup.com/t/9002019994/PRF-6420)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6416 On cysync in history section the "Time" text in header is not left aligned](https://app.clickup.com/t/9002019994/PRF-6416)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6416 On cysync in history section the "Time" text in header is not left aligned](https://app.clickup.com/t/9002019994/PRF-6416)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6416 On cysync in history section the "Time" text in header is not left aligned](https://app.clickup.com/t/9002019994/PRF-6416)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6420 On cysync in settings menu "Analytics and cysync update" section needs to be hidden](https://app.clickup.com/t/9002019994/PRF-6420)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6416 On cysync in history section the "Time" text in header is not left aligned](https://app.clickup.com/t/9002019994/PRF-6416)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6420 On cysync in settings menu "Analytics and cysync update" section needs to be hidden](https://app.clickup.com/t/9002019994/PRF-6420)

**Review by irshadCypherock — APPROVED** [review]

**Pull request merged**
