### PR TITLE
fix: transaction insertion on sync

### PR DESCRIPTION
**Pull request by irshadCypherock**

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6465 On cysync in history page the pending status is not updating to success/fail even after transaction status is updated on explorer and in receiver's account in cysync.](https://app.clickup.com/t/9002019994/PRF-6465)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6466 On cysync in history page the received transaction is not reflecting in cysync.](https://app.clickup.com/t/9002019994/PRF-6466)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6466 On cysync in history page the received transaction is not reflecting in cysync.](https://app.clickup.com/t/9002019994/PRF-6466)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6465 On cysync in history page the pending status is not updating to success/fail even after transaction status is updated on explorer and in receiver's account in cysync.](https://app.clickup.com/t/9002019994/PRF-6465)

**Review by ghost — APPROVED** [review]

**Pull request merged**
